### ISSUE TITLE
Allow integer value for UserAccountControl

### ISSUE THREAD

**Issue by bgre-karlstad** [qtc-de/wconv#4]
UserAccountControl throws a TypeError when passed an integer:

```python
>>> import wconv.uac
>>> wconv.uac.UserAccountControl(512)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Lib\site-packages\wconv\uac.py", line 73, in __init__      
    uac_int = int(uac_value, 0)
              ^^^^^^^^^^^^^^^^^
TypeError: int() can't convert non-string with explicit base
>>> wconv.uac.UserAccountControl(str(512)) 
<wconv.uac.UserAccountControl object at 0x000002DCA9F1E120>
>>> wconv.uac.UserAccountControl(str(512)).flags
['NORMAL_ACCOUNT']
```

Improvement suggestion: make it accept integers

**Comment by qtc-de** [comment]
Resolved with `v2.0.0` :)
